# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8125bce915df57c580780ca26b63f0bb7c14d90ec85cc2bb56136bb687cd094756fecc3752fb4fbc9e5991182beac5cac385957ee104f5515dc376bd32e4916d

test:
  secret_key_base: 244f834f4ecbac41ebc2bca63f488a3b44fb46c789f7e187267ad2f8f78e0b80013741e906438474928ab8c8053c387d723def1adacedc66dda72ae2f5f1149e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
